name: Password Workflow

on: [push]

jobs:
  password_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SECRET_TOKEN
        run: |
          # Retrieve the password from the GitHub secret
          password=$PASSWORD_SECRET

          # Use the password variable in subsequent steps or commands
          echo "Your password is: $password"
